Liquidation of Deposit Funds/force-app/main/default/objects/Case/fields/Account_Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Holder_Name__c</fullName>
    <label>Account Holder Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Liquidation of Deposit Funds/force-app/main/default/objects/Case/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <label>Disbursement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account deposit</fullName>
            </value>
            <value>
                <fullName>Pick-up at branch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Liquidation of Deposit Funds/force-app/main/default/objects/Case/fields/Is_the_sum_all_account_more_than_15k__c.field-meta.xml
<CustomField>
    <fullName>Is_the_sum_all_account_more_than_15k__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is the sum all account more than 15k?</label>
    <type>Checkbox</type>
</CustomField>

Liquidation of Deposit Funds/force-app/main/default/objects/Case/fields/Is_there_a_Will__c.field-meta.xml
<CustomField>
    <fullName>Is_there_a_Will__c</fullName>
    <label>Is there a Will?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes, Will in PR</fullName>
            </value>
            <value>
                <fullName>Yes, Will in USA</fullName>
            </value>
            <value>
                <fullName>No, without Will</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Liquidation of Deposit Funds/force-app/main/default/objects/Case/fields/Other_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Other_Phone_Number__c</fullName>
    <label>Other Phone Number</label>
    <type>Phone</type>
</CustomField>

Liquidation of Deposit Funds/force-app/main/default/objects/Case/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Grandson</fullName>
            </value>
            <value>
                <fullName>Granddaughter</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Aunt</fullName>
            </value>
            <value>
                <fullName>Nephew</fullName>
            </value>
            <value>
                <fullName>Niece</fullName>
            </value>
            <value>
                <fullName>Cousin</fullName>
            </value>
            <value>
                <fullName>Stepfather</fullName>
            </value>
            <value>
                <fullName>Stepmother</fullName>
            </value>
            <value>
                <fullName>Stepbrother</fullName>
            </value>
            <value>
                <fullName>Stepsister</fullName>
            </value>
            <value>
                <fullName>Husband</fullName>
            </value>
            <value>
                <fullName>Wife</fullName>
            </value>
            <value>
                <fullName>Fiancé</fullName>
            </value>
            <value>
                <fullName>Fiancée</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Liquidation of Deposit Funds/force-app/main/default/objects/Case/fields/Social_Security_Number__c.field-meta.xml
<CustomField>
    <fullName>Social_Security_Number__c</fullName>
    <externalId>true</externalId>
    <label>Social Security Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

Liquidation of Deposit Funds/force-app/main/default/classes/CaseController.cls
public with sharing class CaseController {
    public static void createCase(Id accId, Map<String, Object> formData, Map<String, Blob> pdfBlobs) {
        List<Attachment> attachmentList = new List<Attachment>();
        Case newCase = new Case(
            First_Name__c = formData.containsKey('firstName') && (formData.get('firstName') != null || formData.get('firstName') != '')? String.valueOf(formData.get('firstName')): '', 
            Last_Name__c = formData.containsKey('lastName') && (formData.get('lastName') != null || formData.get('lastName') != '')? String.valueOf(formData.get('lastName')): '', 
            Social_Security_Number__c = formData.containsKey('ssn') && (formData.get('ssn') != null || formData.get('ssn') != '')? String.valueOf(formData.get('ssn')): '', 
            Date_of_Death__c = formData.containsKey('dateOfDeath') && (formData.get('dateOfDeath') != null || formData.get('dateOfDeath') != '')? Date.valueOf(String.valueOf(formData.get('dateOfDeath'))): null,
            Relationship__c = formData.containsKey('relationship') && (formData.get('relationship') != null || formData.get('relationship') != '')? String.valueOf(formData.get('relationship')): '',
            Other_Phone_Number__c = formData.containsKey('otherPhoneNumber') && (formData.get('otherPhoneNumber') != null || formData.get('otherPhoneNumber') != '')? String.valueOf(formData.get('otherPhoneNumber')): '',
            Disbursement__c = formData.containsKey('disbursementPreference') && (formData.get('disbursementPreference') != null || formData.get('disbursementPreference') != '')? String.valueOf(formData.get('disbursementPreference')): '',
            AccountId = accId,
            Account_Holder_Name__c = formData.containsKey('accountHolderName') && (formData.get('accountHolderName') != null || formData.get('accountHolderName') != '')? String.valueOf(formData.get('accountHolderName')): '',
            Is_the_sum_all_account_more_than_15k__c	= formData.containsKey('greaterThan15k') && formData.get('greaterThan15k') != null ? Boolean.valueOf(formData.get('greaterThan15k')): false,
            // Is_there_a_Will__c = ,
            Origin ='Liquidation Of Funds Portal'

            );
            insert newCase;
            for(String key : pdfBlobs.keySet()) {
                Blob pdfBlob = pdfBlobs.get(key);
                if(pdfBlob != null){
                    attachmentList.add(
                        new Attachment(
                            Name = key,
                            Body = pdfBlob,
                            ContentType = 'application/pdf',
                            ParentId = newCase.Id
                        )
                    );
                }
            }
        insert attachmentList;
    }
}