Liquidation of Deposit Funds/force-app/main/default/objects/Case/fields/Account_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_First_Name__c</fullName>
    <formula>Account.PersonContact.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account First Name</label>
    <type>Text</type>
</CustomField>

Liquidation of Deposit Funds/force-app/main/default/objects/Case/fields/Account_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Last_Name__c</fullName>
    <formula>Account.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Last Name</label>
    <type>Text</type>
</CustomField>

Liquidation of Deposit Funds/force-app/main/default/objects/Case/fields/Case_Detail_Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Case_Detail_Page_URL__c</fullName>
    <formula>&quot;https://resilient-badger-m2qcfb-dev-ed.trailblaze.my.site.com/LiquidationOfDepositFunds/s/case/&quot; +  Id  + &quot;/detail&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Detail Page URL</label>
    <type>Text</type>
</CustomField>

Liquidation of Deposit Funds/force-app/main/default/classes/ClientCaseController.cls
public with sharing class ClientCaseController {
    
    @AuraEnabled(cacheable=true)
    public static List<Case> getClientCases(){
        try {
            // Query Cases of the current logged in user
            String currentUserEmail = UserInfo.getUserEmail();

            return [
                SELECT Id, CaseNumber, Case_Detail_Page_URL__c, Account_First_Name__c, Account_Last_Name__c, First_Name__c, Last_Name__c, CreatedDate, ContactEmail
                FROM Case
                WHERE ContactEmail = :currentUserEmail
                ORDER BY CreatedDate DESC
            ];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}